### ISSUE TITLE
Change DDL Insert format

### ISSUE THREAD

**Issue by rohanraj-9654** [franklemuchahary/automating_stuff_with_python#3]
SQL Server allows 1000 values Insert in 1 time.
Therefore to completely automate the process and avoid running Insert commands in batches of 1000 values, the format can be changed as below for inserting each row.
INSERT INTO table VALUES (a);
INSERT INTO table VALUES (b);
INSERT INTO table VALUES (c);

**Comment by franklemuchahary** [comment]
Handling this by allowing the user to input batch size as a parameter. Instead of single insert queries for each row, there can be a single batch of insert queries for every 1000 rows or whatever batch size the user needs.
